-- Generated by nwg-displays on 2026-09-28 at 16:12:05. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = 1.0,
    vrr = 0,
    transform = 1
})
hl.monitor({
    output = "DP-2",
    mode = "1920x1080@60.0",
    position = "3000x505",
    scale = 1,
    vrr = 0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "1080x505",
    scale = 1,
    vrr = 0
})
